services:
  - type: web
    name: webapp-fullstack
    env: node
    buildCommand: npm install --prefix services/api && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm run start --prefix services/api
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@webapp.com
      - key: ADMIN_PHONE
        sync: false
      - key: ADMIN_ROLE
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: BCRYPT_ROUNDS
        value: "10"
      - key: ENABLE_DB_INIT
        value: "false"
